name: Cask CI

on:
  pull_request:
    paths:
    - 'Casks/*'

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Cache Homebrew Gems
        uses: actions/cache@v2
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: homebrew-gems-cache-${{  GITHUB_SHA }}
          restore-keys: homebrew-gems-cache-

      - name: Check out Pull Request
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Homebrew Gems
        run: brew install-bundler-gems

      - name: brew audit
        run: |
          brew audit --tap "${GITHUB_REPOSITORY}"
        if: always()

      - name: brew style
        run: |
          brew style "${GITHUB_REPOSITORY}"
        if: always()
